// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} entity
 * @param {string} attributeName
 * @returns {Promise.<string>}
 */
export async function JS_GetCurrentValue(entity, attributeName) {
	// BEGIN USER CODE
	return entity.get(attributeName).toString();
	// END USER CODE
}
