// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import {encode} from 'base64url';
import hash from 'hash.js';
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} stringToHash
 * @returns {Promise.<string>}
 */
export async function JS_HashString(stringToHash) {
	// BEGIN USER CODE
	 	const hashedString = hash.sha256().update(stringToHash).digest('base64');
	    const encodedString = encode(hashedString);

	     return encodedString;
	// END USER CODE
}
