// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Date} dateTime
 * @param {Big} minutesToRound
 * @returns {Promise.<Date>}
 */
export async function JS_RoundMinutes(dateTime, minutesToRound) {
	// BEGIN USER CODE
	var roundoff = 1000 * 60 * minutesToRound;
	return new Date(Math.round(dateTime / roundoff) * roundoff)
	// END USER CODE
}
